// Generated by gencpp from file joh_runtime_monitoring/AddTwoInts.msg
// DO NOT EDIT!


#ifndef JOH_RUNTIME_MONITORING_MESSAGE_ADDTWOINTS_H
#define JOH_RUNTIME_MONITORING_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <joh_runtime_monitoring/AddTwoIntsRequest.h>
#include <joh_runtime_monitoring/AddTwoIntsResponse.h>


namespace joh_runtime_monitoring
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace joh_runtime_monitoring


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::joh_runtime_monitoring::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::joh_runtime_monitoring::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::joh_runtime_monitoring::AddTwoInts > {
  static const char* value()
  {
    return "joh_runtime_monitoring/AddTwoInts";
  }

  static const char* value(const ::joh_runtime_monitoring::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::joh_runtime_monitoring::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::joh_runtime_monitoring::AddTwoInts >
template<>
struct MD5Sum< ::joh_runtime_monitoring::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::joh_runtime_monitoring::AddTwoInts >::value();
  }
  static const char* value(const ::joh_runtime_monitoring::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::joh_runtime_monitoring::AddTwoIntsRequest> should match
// service_traits::DataType< ::joh_runtime_monitoring::AddTwoInts >
template<>
struct DataType< ::joh_runtime_monitoring::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::joh_runtime_monitoring::AddTwoInts >::value();
  }
  static const char* value(const ::joh_runtime_monitoring::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::joh_runtime_monitoring::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::joh_runtime_monitoring::AddTwoInts >
template<>
struct MD5Sum< ::joh_runtime_monitoring::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::joh_runtime_monitoring::AddTwoInts >::value();
  }
  static const char* value(const ::joh_runtime_monitoring::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::joh_runtime_monitoring::AddTwoIntsResponse> should match
// service_traits::DataType< ::joh_runtime_monitoring::AddTwoInts >
template<>
struct DataType< ::joh_runtime_monitoring::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::joh_runtime_monitoring::AddTwoInts >::value();
  }
  static const char* value(const ::joh_runtime_monitoring::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JOH_RUNTIME_MONITORING_MESSAGE_ADDTWOINTS_H
